eastclouddev/Server-API

app/apis/news.py
app/cruds/news.py
app/schemas/news.py
app/tests/apis/test_update_news.py

[TAS-173] ニュース更新API

---

app/apis/reviews.py
app/cruds/reviews.py
app/schemas/reviews.py
app/tests/apis/test_reviews.py

[TAS-432] レビュースレッド詳細API

---

app/apis/companies.py
app/cruds/companies.py
app/schemas/companies.py
app/services/companies.py
app/tests/apis/test_companies.py

[TAS-99] 受講生一覧（法人、法人代行)API

---

app/apis/progresses.py
app/cruds/progresses.py
app/main.py
app/schemas/progresses.py
app/tests/apis/test_progresses.py

[TAS-524] 進捗管理一覧取得API

---

app/apis/curriculums.py
app/cruds/curriculums.py
app/schemas/curriculums.py
app/tests/apis/test_curriculums.py

[TAS-431] レビュー投稿作成API

---

app/apis/questions.py
app/cruds/questions.py
app/schemas/questions.py
app/tests/apis/test_questions.py

[TAS-420] 質問回答更新API

---

app/apis/companies.py
app/cruds/companies.py
app/schemas/companies.py
app/tests/apis/test_companies.py

[TAS-525] 進捗管理一覧取得API（法人、法人代行）

---

app/apis/mentors.py
app/cruds/mentors.py
app/schemas/mentors.py
app/tests/apis/test_mentors.py

[TAS-526] 進捗管理一覧（メンター）

---

app/apis/curriculums.py
app/cruds/curriculums.py
app/schemas/curriculums.py
app/tests/apis/test_curriculums.py

[TAS-184] テスト詳細API

---

app/apis/questions.py
app/cruds/questions.py
app/schemas/questions.py
app/tests/apis/test_questions.py

[TAS-419] 質問更新API

---

app/apis/curriculums.py
app/cruds/curriculums.py
app/schemas/curriculums.py
app/tests/apis/test_curriculums.py

[TAS-110] 質問一覧API

---

app/apis/logout.py
app/cruds/logout.py
app/tests/apis/test_logout.py

[PR-745]  ログアウト時にトークン削除

---

app/apis/users.py
app/cruds/users.py
app/schemas/users.py
app/tests/apis/test_users.py

[PR-812]：有効アカウント数取得

---

app/apis/courses.py
app/cruds/courses.py
app/schemas/courses.py
app/tests/apis/test_courses.py

[PR-815]：コース開始API実装完了

---

app/apis/students.py
app/cruds/students.py
app/tests/apis/test_students.py

[PR-818]: 受講生と担当メンターの関連づけAPI実装完了

---

app/main.py
requirements.txt

本タイミングで画面との連携ができないため、仮の実装です。
機能の使い方や処理の書き方を記述したものです。

[PR-816]：websocketの設定（仮実装）

---

app/apis/mentors.py
app/cruds/mentors.py
app/schemas/mentors.py
app/tests/apis/test_mentors.py

[PR-825]: メンター担当受講者数取得API実装完了

---

app/apis/companies.py
app/apis/mentors.py
app/cruds/companies.py
app/cruds/mentors.py
app/schemas/companies.py
app/schemas/mentors.py
app/tests/apis/test_companies.py
app/tests/apis/test_mentors.py

[PR-824]: 有効アカウント数(法人、法人代行)取得API実装完了

---

app/apis/news.py
app/cruds/news.py
app/models/news_categories.py
app/models/notifications.py
app/schemas/news.py
app/tests/apis/test_news.py

[PR-853]: ニュースカテゴリ作成API実装完了

---

app/apis/companies.py
app/cruds/companies.py
app/schemas/companies.py
app/tests/apis/test_companies.py

[PR-240]: 請求書履歴一覧API実装完了

---

app/apis/companies.py
app/apis/courses.py
app/apis/mentors.py
app/apis/progresses.py
app/apis/students.py
app/cruds/companies.py
app/cruds/courses.py
app/cruds/mentors.py
app/cruds/progresses.py
app/cruds/students.py

ご確認、宜しくお願いします。
[PR-888]
・コース一覧(courses.py)
・質問一覧(courses.py)
・自分のレビュー一覧(students.py)
[PR-893]
・自分の質問一覧(students.py)
・進捗一覧(companies.py, mentors.py, progresses.py)
・請求履歴一覧(companies.py)

[PR-888]フィルター・ソート・検索機能の追加

---

app/apis/billing_summary.py
app/cruds/billing_summary.py
app/main.py
app/schemas/billing_summary.py
app/tests/apis/test_billing_summary.py

遅れてしまい申し訳ありません。
ご確認よろしくお願い致します。

[PR-826]: 先月の請求金額合計取得API実装完了

---

app/apis/companies.py
app/apis/mentors.py
app/apis/users.py
app/cruds/companies.py
app/cruds/mentors.py
app/cruds/users.py
app/services/companies.py

以下のAPIにフィルター・ソート・検索機能を追加しました。
- ユーザー一覧（/users）
- ユーザー一覧（/companies/{company_id}/users）
- 会社一覧（/companies）
メンター一覧に関してはAPIの再設計が必要なため、未着手です。

[PR-894]：フィルター・ソート・検索機能の実装
